Merge remote-tracking branch 'origin/97019-Content-Changes' into feat…
DFE-Digital/academy-transfers-api pull request #370
Opened 2022-07-22 13:29 UTC by MosesOkoruwaDfE

…ure/100585-transfers-content-advisory-board

### Context

### Changes proposed in this pull request

### Checklist

- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally

2022-07-28 09:58 UTC, jordan-beard commented on Frontend/Pages/Home/Index.cshtml
> -        <h3 class="govuk-heading-m">
Did you meant to remove this h3?

2022-07-28 09:58 UTC, jordan-beard commented on Frontend/Pages/Projects/TransferDates/AdvisoryBoard.cshtml.cs
> +            projectResult.Dates.Htb = AdvisoryBoardViewModel.AdvisoryBoardDate.DateInputAsString();
Whitespace

2022-07-28 10:01 UTC, jordan-beard commented on Frontend/Pages/Projects/TransferDates/AdvisoryBoard.cshtml.cs
> +            if(!string.IsNullOrEmpty(projectResult.Dates.HtbInserted))
To save space you could use the ternary operator
`projectResult.Dates.HasHtbInserted = !string.IsNullOrEmpty(projectResult.Dates.HtbInserted) 
? true
: false`

2022-07-28 10:02 UTC, jordan-beard requested changes
A few small things.

2022-07-28 13:57 UTC, jordan-beard approved these changes

2022-07-29 13:20 UTC, jordan-beard approved these changes

2022-07-29 14:01 UTC, MartinWheelerMT approved these changes

2022-08-01 13:49 UTC, closed without merging